<?php
$allUsersList = $db->get('users');
?>
<div class="container-fluid" id="vc_chat_container_admin">
    <div>
        <h3>ALL user logins</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">All user login</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
      <div class="col-md-12">
          <div class="card">
              <div class="card-body">
                  <h6 class="card-title">Select User</h6>
                  <div class="d-flex align-items-center mb-3">
                      <select name="selectActiveUser" class="form-control show-tick" onchange="chat_convList_refreshFunction()" id="selectActiveUser">
                        <?php
                            foreach ($allUsersList as $eachUser) {
                                echo '<option value="'.$eachUser['id'].'">'.$eachUser['username'].'( '.$eachUser['first_name'].' '. $eachUser['last_name'].' )</option>';
                            }
                        ?>
                        
                      </select>
                  </div>
              </div>
          </div>
      </div>

        
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                  <h6 class="card-title" id="vc_chat_title">All Sessions</h6>
                    <div class="clearfix"></div>
                    
                    <div class="row" id="vc_alluserlogin_content_wrapper">
                        <div class="col-lg-12">
                            <div>
                                <div>
                                    <div class="session_row valign-wrapper qd_sett_sessions">
                                        <div class="valign-wrapper first">
                                            &nbsp;&nbsp;&nbsp;&nbsp;<div><b>Platform</b> </div>
                                        </div>
                                        <div>
                                            <p><b>IP Address</b></p>
                                        </div>
                                        
                                        <div>
                                            <p><b>Login time</b></p>
                                        </div>
                                        <div>
                                            <p><b>Status</b></p>
                                        </div>
                                    </div>
                                <?php
                                    global $db;
                                    $sessions = $db->where('user_id',$allUsersList[0]['id'])->orderBy('time', 'DESC')->get('admin_sessions2', null, array('*'));
                                    foreach ($sessions as $key => $session) {
                                        $details = unserialize($session['platform_details']);
                                        echo '<div class="session_row valign-wrapper qd_sett_sessions" data-id="'.$session['id'].'">';
                                        echo '<div class="valign-wrapper first">';
                                        switch (strtolower($details['platform'])) {
                                            case 'windows':
                                                echo '<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,15 L23,15 L23,18 C23,19.1045695 22.1045695,20 21,20 L3,20 C1.8954305,20 1,19.1045695 1,18 L1,15 L3,15 L3,6 C3,4.8954305 3.8954305,4 5,4 L19,4 C20.1045695,4 21,4.8954305 21,6 L21,15 Z M19,15 L19,6 L5,6 L5,15 L19,15 Z M3,17 L3,18 L21,18 L21,17 L3,17 Z" fill="#D21312"/></svg></span>&nbsp;&nbsp;&nbsp;&nbsp;';
                                                break;
                                            case 'linux':
                                                echo '<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,15 L23,15 L23,18 C23,19.1045695 22.1045695,20 21,20 L3,20 C1.8954305,20 1,19.1045695 1,18 L1,15 L3,15 L3,6 C3,4.8954305 3.8954305,4 5,4 L19,4 C20.1045695,4 21,4.8954305 21,6 L21,15 Z M19,15 L19,6 L5,6 L5,15 L19,15 Z M3,17 L3,18 L21,18 L21,17 L3,17 Z" fill="#D21312"/></svg></span>&nbsp;&nbsp;&nbsp;&nbsp;';
                                                break;
                                            case 'mac':
                                                echo '<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,15 L23,15 L23,18 C23,19.1045695 22.1045695,20 21,20 L3,20 C1.8954305,20 1,19.1045695 1,18 L1,15 L3,15 L3,6 C3,4.8954305 3.8954305,4 5,4 L19,4 C20.1045695,4 21,4.8954305 21,6 L21,15 Z M19,15 L19,6 L5,6 L5,15 L19,15 Z M3,17 L3,18 L21,18 L21,17 L3,17 Z" fill="#D21312"/></svg></span>&nbsp;&nbsp;&nbsp;&nbsp;';
                                                break;
                                            case 'iphone web':
                                                echo '<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7,1 L17,1 C18.1045695,1 19,1.8954305 19,3 L19,21 C19,22.1045695 18.1045695,23 17,23 L7,23 C5.8954305,23 5,22.1045695 5,21 L5,3 C5,1.8954305 5.8954305,1 7,1 Z M10,3 L7,3 L7,21 L17,21 L17,3 L14,3 C14,3.55228475 13.5522847,4 13,4 L11,4 C10.4477153,4 10,3.55228475 10,3 Z" fill="#D21312"/></svg></span>&nbsp;&nbsp;&nbsp;&nbsp;';
                                                break;
                                            case 'android web':
                                                echo '<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7,1 L17,1 C18.1045695,1 19,1.8954305 19,3 L19,21 C19,22.1045695 18.1045695,23 17,23 L7,23 C5.8954305,23 5,22.1045695 5,21 L5,3 C5,1.8954305 5.8954305,1 7,1 Z M10,3 L7,3 L7,21 L17,21 L17,3 L14,3 C14,3.55228475 13.5522847,4 13,4 L11,4 C10.4477153,4 10,3.55228475 10,3 Z" fill="#D21312"/></svg></span>&nbsp;&nbsp;&nbsp;&nbsp;';
                                                break;
                                            case 'mobile':
                                                echo '<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7,2 L17,2 C18.1045695,2 19,2.8954305 19,4 L19,20 C19,21.1045695 18.1045695,22 17,22 L7,22 C5.8954305,22 5,21.1045695 5,20 L5,4 C5,2.8954305 5.8954305,2 7,2 Z M7,4 L7,20 L17,20 L17,4 L7,4 Z M12,19 C11.4477153,19 11,18.5522847 11,18 C11,17.4477153 11.4477153,17 12,17 C12.5522847,17 13,17.4477153 13,18 C13,18.5522847 12.5522847,19 12,19 Z" fill="#D21312"/></svg></span>&nbsp;&nbsp;&nbsp;&nbsp;';
                                                break;
                                            case 'phone':
                                                echo '<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7,2 L17,2 C18.1045695,2 19,2.8954305 19,4 L19,20 C19,21.1045695 18.1045695,22 17,22 L7,22 C5.8954305,22 5,21.1045695 5,20 L5,4 C5,2.8954305 5.8954305,2 7,2 Z M7,4 L7,20 L17,20 L17,4 L7,4 Z M12,19 C11.4477153,19 11,18.5522847 11,18 C11,17.4477153 11.4477153,17 12,17 C12.5522847,17 13,17.4477153 13,18 C13,18.5522847 12.5522847,19 12,19 Z" fill="#D21312"/></svg></span>&nbsp;&nbsp;&nbsp;&nbsp;';
                                                break;
                                            case 'unknown':
                                                echo '<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M21,7 C22.1045695,7 23,7.8954305 23,9 L23,18 C23,19.1045695 22.1045695,20 21,20 L16,20 L3,20 C1.8954305,20 1,19.1045695 1,18 L1,15 L3,15 L3,6 C3,4.8954305 3.8954305,4 5,4 L19,4 C20.1045695,4 21,4.8954305 21,6 L21,7 Z M19,7 L19,6 L5,6 L5,15 L14,15 L14,9 C14,7.8954305 14.8954305,7 16,7 L19,7 Z M14,18 L14,17 L3,17 L3,18 L14,18 Z M16,9 L16,18 L21,18 L21,9 L16,9 Z" fill="#D21312"/></svg></span>&nbsp;&nbsp;&nbsp;&nbsp;';
                                                break;
                                        }
                                        echo '<div>';
                                        echo '<b>'.$details['platform'].'</b>';
                                        echo '<p>';
                                        echo '<svg xmlns="http://www.w3.org/2000/svg" width="19.301" height="17.301" viewBox="0 0 19.301 17.301"> <path d="M18.651,17.3H.65a.69.69,0,0,1-.463-.187A.69.69,0,0,1,0,16.65V.65A.685.685,0,0,1,.187.188.683.683,0,0,1,.65,0h18a.68.68,0,0,1,.461.188A.68.68,0,0,1,19.3.65v16a.641.641,0,0,1-.65.65ZM1.3,7.3V16H18V7.3Zm0-6V6H18V1.3Zm7,3H7V3H8.3V4.3Zm-4,0H3V3H4.3V4.3Z" fill="currentColor"/> </svg>&nbsp;&nbsp;<span>'.$details['name'].'</span>';
                                        echo '</p>';
                                        echo '</div>';
                                        echo '</div>';
                                        echo '<div>';
                                        echo '<p>';
                                        echo '<svg xmlns="http://www.w3.org/2000/svg" width="19.3" height="19.3" viewBox="0 0 19.3 19.3"> <path d="M10.21,19.3H9.091V17.467l-.313-.034a7.876,7.876,0,0,1-6.91-6.91l-.034-.312H0V9.091H1.833l.034-.312a7.875,7.875,0,0,1,6.91-6.91l.313-.035V0H10.21V1.833l.311.035a7.876,7.876,0,0,1,6.912,6.91l.034.313H19.3V10.21H17.467l-.034.313a7.877,7.877,0,0,1-6.912,6.91l-.311.034V19.3ZM9.65,2.94a6.71,6.71,0,1,0,6.71,6.71A6.718,6.718,0,0,0,9.65,2.94Zm0,10a3.29,3.29,0,1,1,3.29-3.29A3.294,3.294,0,0,1,9.65,12.94Z" fill="currentColor"/> </svg>&nbsp;&nbsp;<span>'.$session['ip_address'].'</span>';
                                        echo '</p>';
                                        echo '</div>';
                                        echo '<div>';
                                        echo '<p>';
                                        echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="18" height="18"><path fill="none" d="M0 0h24v24H0z"/><path fill="currentColor" d="M1.181 12C2.121 6.88 6.608 3 12 3c5.392 0 9.878 3.88 10.819 9-.94 5.12-5.427 9-10.819 9-5.392 0-9.878-3.88-10.819-9zM12 17a5 5 0 1 0 0-10 5 5 0 0 0 0 10zm0-2a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/></svg>&nbsp;&nbsp;<span class="ajax-time" title="'.date('c',$session['time']).'">'.Time_Elapsed_String($session['time']).'</span>';
                                        echo '</p>';
                                        echo '</div>';
                                        echo '<div>';
                                        echo '<p>';
                                        echo ' &nbsp;&nbsp;<span>'.($session['status']==1? 'Active':'logged Out').'</span>';
                                        echo '</p>';
                                        echo '<p>';
                                        if($session['outtime']> 0){
                                            echo '&nbsp;&nbsp;<span class="ajax-time" title="'.date('c',$session['outtime']).'">'.Time_Elapsed_String($session['outtime']).'</span>';
                                        }
                                        echo '</p>';
                                        echo '</div>';
                                        echo '</div>';
                                    }
                                ?>
                                </div>
                                <br><br><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>


<script>
jQuery(document).ready(function($) {
});
        
function chat_convList_refreshFunction(a, b) {
    let selectActiveUser = $('#selectActiveUser');
    selectActiveUser.disabled = true;
    $('#vc_chat_title').html('Loading Session for user'+ selectActiveUser.find(":selected").text());
    

    var url = '?path=vs_alluserlogin_ajax';
    $.post(Wo_Ajax_Requests_File_load() + url, {url:url,ref:selectActiveUser.val(),type:'load'}, function (data) {
        json_data = JSON.parse($(data).filter('#json-data').val());
        $('#vc_alluserlogin_content_wrapper').html(data);
        $('#vc_chat_title').html('All Sessions');
    });
            

}



</script>